const courses = [
  "Bachelor of Arts in History",
  "Bachelor of Arts in Philosophy",
  "Bachelor of Fine Arts Major in Industrial Design",
  "Bachelor of Fine Arts Major in Painting",
  "Bachelor of Fine Arts Major in Sculpture",
  "Bachelor of Fine Arts Major in Visual Communication",
  "Bachelor of Arts in Economics",
  "Bachelor of Science in Economics",
  "Bachelor of Arts in Psychology",
  "Bachelor of Science in Psychology",
  "Bachelor of Science in Criminology",
  "Bachelor of Science in Political Science",
  "Bachelor of Arts in English",
  "Bachelor of Arts in Linguistic",
  "Bachelor of Arts in literature",
  "Bachelor of Science in Forensic science",
  "Bachelor of Arts in Islamic Studies",
  "Bachelor of Science in Environmental Science",
  "Bachelor of Science in Forestry",
  "Bachelor of Science in Fisheries",
  "Bachelor of Science in Geology",
  "Bachelor of Science in Biology",
  "Bachelor of Science in Molecular Biology",
  "Bachelor of Science in Physics",
  "Bachelor of Science in Chemistry",
  "Bachelor of Science in Computer science",
  "Bachelor of Science in Information Technology",
  "Bachelor of Science in Information System",
  "Bachelor of Science in Mathematics",
  "Bachelor of Science in Applied Mathematics",
  "Bachelor of Science in Statistics",
  "Bachelor of Science in Agriculture",
  "Bachelor of Science in Agribusiness",
  "Bachelor of Science in Agroforestry",
  "Bachelor of Science in Architecture",
  "Bachelor of Science in Interior design",
  "Bachelor in Landscape Architecture",
  "Bachelor of Science in Accountancy",
  "Bachelor of Science in Accounting Technology",
  "Bachelor of Science in Business Administration",
  "Bachelor of Science in Business Administration Major in Business Economics",
  "Bachelor of Science in Business Administration Major in Financial management",
  "Bachelor of Science in Business Administration Major in. Human Resource Development",
  "Bachelor of Science in Business Administration Major in Marketing management",
  "Bachelor of Science in Business Administration Major in Operation management",
  "Bachelor of Science in Business Administration Major in Hotel and Restaurant Management",
  "Bachelor of Science in Entrepreneurship",
  "Bachelor of Science in Office Administration",
  "Bachelor of Science in Real Estate Management",
  "Bachelor of Science in Tourism Management",
  "Bachelor of Science in Medical Technology",
  "Bachelor of Science in Midwifery",
  "Bachelor of Science in Nursing",
  "Bachelor of Science in Occupational Therapy",
  "Bachelor of Science in Pharmacy",
  "Bachelor of Science in Physical therapy",
  "Bachelor of Science in Radiologic Technology",
  "Bachelor of Science in Respiratory Therapy",
  "Bachelor of Science in Speech Language Pathology",
  "Bachelor of Science in Sports Science",
  "Bachelor of Science in Secondary Education",
  "Bachelor of Elementary Education",
  "Bachelor of Science in Secondary Education Major in Technology Livelihood Education",
  "Bachelor of Science in Secondary Education Major in Biological Sciences",
  "Bachelor of Science in Secondary Education Major in English",
  "Bachelor of Science in Secondary Education Major in Filipino",
  "Bachelor of Science in Secondary Education Major in Mathematics",
  "Bachelor of Science in Secondary Education Major in Islamic Studies",
  "Bachelor of Science in Secondary Education Major in Music, arts, Physical and Health Education",
  "Bachelor of Science in Secondary Education Major in Physical Sciences",
  "Bachelor of Science in Secondary Education Major in  Social Studies",
  "Bachelor of Science in Secondary Education Major in Values Education",
  "Bachelor of Elementary Education Major in Preschool Education",
  "Bachelor of Library and Information Science in the Philippines",
  "Bachelor of Physical Education",
  "Bachelor of science in Aeronautical Engineering",
  "Bachelor of science in Ceramic Engineering",
  "Bachelor of science in Chemical Engineering",
  "Bachelor of science in Civil Engineering",
  "Bachelor of science in Computer Engineering",
  "Bachelor of science in Electrical Engineering",
  "Bachelor of science in Electronics and Communication Engineering",
  "Bachelor of science in Geodetic Engineering",
  "Bachelor of science in Geological Engineering",
  "Bachelor of science in Industrial Engineering",
  "Bachelor of science in Marine Engineering",
  "Bachelor of science in Materials Engineering",
  "Bachelor of science in Mechanical Engineering",
  "Bachelor of science in Metallurgical Engineering",
  "Bachelor of science in Mining Engineering",
  "Bachelor of science in Petroleum Engineering",
  "Bachelor of science in Sanitary Engineering",
  "Bachelor of Arts in Broadcasting",
  "Bachelor of Arts in Communication",
  "Bachelor of Arts in Development Communication",
  "Bachelor of Arts in Mass Communication",
  "Bachelor of Arts in Journalism",
  "Bachelor of Science in Community Development",
  "Bachelor of Science in Custom Administration",
  "Bachelor of Science in Foreign Service",
  "Bachelor of Science in International Studies",
  "Bachelor of Science in Public Safety",
  "Bachelor of Science in Social Work",
  "Bachelor of Public Administration",
  "Bachelor of Science in Marine Transportation",
  "Bachelor of Science in Food Technology",
  "Bachelor of Science in Nutrition and Dietetics",
];

export default courses;
